version: '3'
services:

    mariadb:
      build: 
        context: /home/zsarir/Desktop/Inception/srcs/requirements/mariadb
        args:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
      image: mariadb
      container_name: mariadb
      env_file: .env
      volumes:
        - db:/var/lib/mysql
      restart: always
      networks: 
      - mynet

    wordpress:
      build: 
       context: /home/zsarir/Desktop/Inception/srcs/requirements/wordpress
       args:
           MYSQL_USER: $MYSQL_USER
           MYSQL_PASSWORD: $MYSQL_PASSWORD
           ADMIN_USER: $ADMIN_USER
           ADMIN_PASSWORD: $ADMIN_PASSWORD
      image: wordpress
      container_name: wordpress
      restart: always
      depends_on:
      - mariadb
      volumes:
      - wordpress:/var/www/html
      env_file: .env
      networks: 
      - mynet

    nginix:
      build:
        context: /home/zsarir/Desktop/Inception/srcs/requirements/nginx
      image: nginix
      container_name: nginix
      ports:
      - 443:443
      volumes:
      - wordpress:/var/www/html
      restart: always
      depends_on:
      - wordpress
      networks: 
      - mynet

    adminer:
      build:
        context: /home/zsarir/Desktop/Inception/srcs/requirements/bonus/adminer
      image: adminer
      container_name: adminer
      ports:
      - 8080:8080
      restart: always
      depends_on:
      - mariadb
      networks: 
      - mynet
 
    redis:
      build:
        context: /home/zsarir/Desktop/Inception/srcs/requirements/bonus/redis
      image: redis
      container_name: redis
      restart: always
      networks: 
      - mynet

    website:
      build:
        context: /home/zsarir/Desktop/Inception/srcs/requirements/bonus/website
      image: website
      container_name: website
      ports:
      - "80:80"
      restart: always
      networks: 
      - mynet

    ftp_server:
      build:
        context: /home/zsarir/Desktop/Inception/srcs/requirements/bonus/ftp_server
      image: ftp_server
      container_name: ftp_server
      restart: always
      ports:
      - "20:20"
      - "21:21"
      - "10000-10100:10000-10100"
      depends_on:
      - wordpress
      volumes:
      - wordpress:/home/zsarir
      networks: 
      - mynet

    cadvisor:
      build: ./requirements/bonus/cadvisor
      container_name: cadvisor
      image: cadvisor
      restart: always
      ports:
        - 2000:2000
      volumes:
        - "/:/rootfs:ro"
        - "/var/run:/var/run:rw"
        - "/sys:/sys:ro"
        - "/var/lib/docker/:/var/lib/docker:ro"
      networks:
        - mynet



volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/zsarir/data/db
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /home/zsarir/data/wordpress

networks:
  mynet:
    driver: bridge

