version: '3'
services:
    mariadb:
      build: /Users/zsarir/Desktop/Inception/srcs/requirements/mariadb
      restart: always #containers have to restart in case of a crash.
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_USER: zsarir
        MYSQL_PASSWORD: 1234
      volumes:
        - db:/var/lib/mysql
      ports:
        - 3306:3306
      # network: mynet

    # wordpress:
    #   depends_on:
    #     - mariadb
    #   image: wordpress
    #   restart: always
    #   ports: 
    #     - "8080:80"
    #   environment:
    #     WORDPRESS_DB_HOST: mariadb:3360
    #     WORDPRESS_DB_USER: wp_user
    #     WORDPRESS_DB_PASSWORD: 1234
    #     WORDPRESS_DB_NAME: wp_db
    #   volumes:
    #   - WordPress:/var/www/html
volumes:
  db:

