version: '3'
services:

    mariadb:
      build: 
        context: /Users/zsarir/Desktop/Inception/srcs/requirements/mariadb
        args:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
      image: mariadb
      container_name: mariadb
      env_file: .env
      volumes:
        - db:/var/lib/mysql
      restart: always
      networks: 
      - mynet

    wordpress:
      build: 
       context: /Users/zsarir/Desktop/Inception/srcs/requirements/wordpress
       args:
           MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
           MYSQL_USER: $MYSQL_USER
           MYSQL_PASSWORD: $MYSQL_PASSWORD
           ADMIN_USER: $ADMIN_USER
           ADMIN_PASSWORD: $ADMIN_PASSWORD
      image: wordpress
      container_name: wordpress
      restart: always
      depends_on:
      - mariadb
      volumes:
      - wordpress:/var/www/html
      env_file: .env
      networks: 
      - mynet

    nginix:
      build:
        context: /Users/zsarir/Desktop/Inception/srcs/requirements/nginx
      image: nginix
      container_name: nginix
      ports:
      - 443:443
      volumes:
      - wordpress:/var/www/html
      restart: always
      depends_on:
      - wordpress
      networks: 
      - mynet

volumes:
  db:
    driver_opt:
      type: none
      o: bind
      device: /home/login/data/db
  wordpress:
    driver_opt:
      type: none
      o: bind
      device: /home/login/data/wordpress

networks:
  mynet:
    driver: bridge

